repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev:  v1.43.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args: ['--args=--required=false', '--args=--sort=false']